hw_quotes/hw_quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('users/', include('users.urls')),
    path('author/', include('quotes.urls')),
]

hw_quotes/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path('', views.main, name='home'),
    path('<int:page>', views.main, name='root_paginate'),
    path('author/<int:_id>/', views.author_about, name='author_about'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_tag/', views.add_tag, name='add_tag'),
    path('tag/<int:_id>/', views.find_by_tag, name='find_by_tag'),
]

hw_quotes/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path
from .forms import LoginForm
from .views import RegisterView

app_name = 'users'

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='register'),
    path('signin/', LoginView.as_view(
        template_name='users/signin.html',
        authentication_form=LoginForm,
        redirect_authenticated_user=True
    ), name='login'),
    path('logout/', LogoutView.as_view(
            template_name='users/logout.html',
        ), name='logout'),
]

hw_quotes/quotes/models.py
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=150)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

hw_quotes/users/models.py
from django.db import models

# Create your models here.

hw_quotes/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, ModelMultipleChoiceField, ModelChoiceField, Select, \
    SelectMultiple
from .models import Quote, Author, Tag


class QuoteForm(ModelForm):
    quote = CharField(min_length=5, required=True, widget=TextInput())
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all().order_by("name"), required=True,
                                    widget=SelectMultiple())
    author = ModelChoiceField(queryset=Author.objects.all().order_by("fullname"), widget=Select())

    class Meta:
        model = Quote
        fields = ['quote', 'tags', 'author']


class AuthorForm(ModelForm):
    fullname = CharField(max_length=50, widget=TextInput())
    born_date = CharField(max_length=50, widget=TextInput())
    born_location = CharField(max_length=150, widget=TextInput())
    description = CharField(widget=TextInput())

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class TagForm(ModelForm):
    name = CharField(max_length=50, widget=TextInput())

    class Meta:
        model = Tag
        fields = ["name"]

hw_quotes/users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django import forms


class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=50, required=True, widget=forms.TextInput({'class': 'form-control'}))
    email = forms.CharField(max_length=50, required=True, widget=forms.EmailInput({'class': 'form-control'}))
    password1 = forms.CharField(max_length=50, min_length=5, required=True,
                                widget=forms.PasswordInput({'class': 'form-control'}))
    password2 = forms.CharField(max_length=50, min_length=5, required=True,
                                widget=forms.PasswordInput({'class': 'form-control'}))

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=50, required=True, widget=forms.TextInput({'class': 'form-control'}))
    password = forms.CharField(max_length=50, min_length=5, required=True,
                               widget=forms.PasswordInput({'class': 'form-control'}))

    class Meta:
        model = User
        fields = ["username", "password"]

hw_quotes/quotes/views.py
from django.core.paginator import Paginator
from django.db.models import Count
from django.shortcuts import render, redirect
from .models import Author, Quote, Tag
from .utils import get_mongodb
from .forms import QuoteForm, AuthorForm, TagForm

raw_sql_query_top_tags = """
SELECT quotes_tag.id as id, quotes_tag.name
FROM quotes_quote_tags
join quotes_tag on quotes_tag.id = quotes_quote_tags.tag_id 
group by quotes_tag.name, quotes_tag.id
order by count(quotes_quote_tags.tag_id) desc, quotes_tag.name
limit 10
"""

top_tags = Tag.objects.raw(raw_sql_query_top_tags)


def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(list(quotes), per_page)
    quotes_on_page = paginator.page(page)
    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})


def author_about(request, _id):
    print(_id)
    author = Author.objects.get(pk=_id)
    print(author.fullname, type(author))

    return render(request, 'quotes/author.html', context={'author': author})


def add_quote(request):
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            return redirect(to="quotes:home")
        else:
            return render(request, "quotes/add_quote.html", context={'form': QuoteForm(), "message": "Form not valid"})
    return render(request, "quotes/add_quote.html", context={'form': QuoteForm()})


def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            return redirect(to="quotes:home")
        else:
            return render(request, "quotes/add_author.html",
                          context={'form': AuthorForm(), "message": "Form not valid"})
    return render(request, "quotes/add_author.html", context={'form': AuthorForm()})


def add_tag(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            new_quote = form.save()
            return redirect(to="quotes:home")
        else:
            return render(request, "quotes/add_tag.html", context={'form': TagForm(), "message": "Form not valid"})
    return render(request, "quotes/add_tag.html", context={'form': TagForm()})


def find_by_tag(request, _id):
    per_page = 5
    quotes = Quote.objects.filter(tags=_id).all()
    paginator = Paginator(list(quotes), per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    top_tags = Tag.objects.raw(raw_sql_query_top_tags)
    for tag in top_tags:
        print(tag.id, tag.name)

    return render(request, "quotes/index.html", context={'quotes': page_obj, 'top_tags': top_tags})

hw_quotes/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages

from .forms import RegisterForm


class RegisterView(View):
    form_class = RegisterForm
    template_name = 'users/signup.html'

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, f"Hello {username}! Your account has been created.")
            return redirect(to="users:login")
        return render(request, self.template_name, {'form': form})

hw_quotes/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_author' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Fullname:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born Date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label> Born Location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label> Description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

hw_quotes/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Author:
            {{ form.author }}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Tags:
            {{ form.tags }}
        </label>
        <span>{{ form.errors.tags }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

hw_quotes/quotes/templates/quotes/add_tag.html
 {% extends "quotes/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotes:add_tag' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Tags:
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

hw_quotes/quotes/templates/quotes/author.html
{% extends "quotes/base.html" %}
{% block content %}
<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p>
        <strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span>
        <span class="author-born-location">{{author.born_location}}</span>
    </p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.description}}
    </div>
</div>
{% endblock %}

hw_quotes/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="/static/quotes/img/ua.ico">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Homework 10</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">

            <h1>
                <a href="/" style="text-decoration: none">Quotes to Scrape</a>
            </h1>
        </div>
        <div class="col-md-4">
            <p>
                {% if user.is_authenticated %}
                <a href="/users/logout" class="btn btn-light">Logout</a>
                <a href="{% url 'quotes:add_quote' %}" class="btn btn-info">Add Quote</a>
                <a href="{% url 'quotes:add_author' %}" class="btn btn-info">Add Author</a>
                <a href="{% url 'quotes:add_tag' %}" class="btn btn-info">Add Tag</a>
                {% else %}
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                <a href="/users/signup" class="btn btn-light">Signup</a>
                <a href="/users/signin" class="btn btn-light">Login</a>
                {% endif %}
            </p>
        </div>
    </div>

    {% block content %} {% endblock %}

</div>
</body>
</html>

hw_quotes/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}
{% load extract %}

{% block content %}
<div class="row mb-3">
    <div class="col-md-8 themed-gris-col">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
        <a href="{% url 'quotes:author_about' quote.author.id %}">(about)</a>
        </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:find_by_tag' tag.id %}">{{tag}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
        <nav>
      <ul class="pager">

            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                <span aria-hidden="true">←</span> Previous</a>
            </li>


            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}"
                href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                Next <span aria-hidden="true">→</span></a>
            </li>

        </ul>
    </nav>
    </div>
    <div class="col-md-4 tags-box">
        <h2>Top Ten tags</h2>
        <span class="tag-item">
            {% for tag in top_tags %}
                <a class="tag" href="{% url 'quotes:find_by_tag' tag.id %}">{{tag}}</a>
                <p></p>
            {% endfor %}
        </span>
    </div>

</div>


{% endblock %}

hw_quotes/users/templates/users/logout.html
{% extends 'quotes/base.html' %}

{% block content %}

<h3>Good bye</h3>

{% endblock %}

hw_quotes/users/templates/users/signin.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>SignIn</h2>

{% if form.errors %}
<span class="alert alert-danger" role="alert">{{form.non_field_errors}}</span>
{% endif %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %} role="alert">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form method="post">
    {% csrf_token %}

    <div class="row mb-4">
        <label>Username:</label>
        {{form.username}}
        <span>{{form.errors.username}}</span>
    </div>
    <div class="row mb-3">
        <label>Password:</label>
        {{form.password}}
        <span>{{form.errors.password}}</span>
    </div>
    <div class="d-grid gap-2 col-6 mx-auto">
        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
        <button type="reset" class="btn btn-secondary btn-sm">Reset</button>
    </div>
</form>

{% endblock %}

hw_quotes/users/templates/users/signup.html
{% extends 'quotes/base.html' %}

{% block content %}

<h2>SignUp</h2>

{% if form.errors %}
<span class="alert alert-danger" role="alert">{{ form.non_field_errors }}</span>
{% endif %}

<form method="post">
    {% csrf_token %}

    <div class="row mb-4">
        <label>Username:</label>
        {{ form.username }}
        <span>{{ form.errors.username }}</span>
    </div>
    <div class="row mb-3">
        <label>Email:</label>
        {{ form.email }}
        <span>{{ form.errors.email }}</span>
    </div>
    <div class="row mb-3">
        <label>Password:</label>
        {{ form.password1 }}
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div class="row mb-3">
        <label>Password:</label>
        {{ form.password2}}
        <span>{{ form.errors.password2 }}</span>
    </div>

    <div class="d-grid gap-2 col-6 mx-auto">
        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
        <button type="reset" class="btn btn-secondary btn-sm">Reset</button>
    </div>
</form>

{% endblock %}